### ISSUE TITLE
use c++-2a for gcc-9 and earlier

### ISSUE THREAD

**Issue by ClementPinard** [nikolausmayer/hanabi#1]
Hi, thanks for this nice little game, love it !

Tried to compile it on ubuntu 20.04 with g++-9 and had to change c++20 to c++2a [here](https://github.com/nikolausmayer/hanabi/blob/main/Makefile#L14)

Not sure how to make it robust to older versions of g++ though (I have zero knowledge of Makefile syntaxe ! :p)

**Comment by nikolausmayer** [comment]
Thanks, and thanks! :wink: 

`c++2a` works for g++-8. 
g++-7 does not support C++20 so that's where compatibility ends (even though I'm not actually using any C++20 features at the moment).
A truly robust version should probably use a more proper system like CMake..
